### ISSUE TITLE
AX3000v2

### ISSUE THREAD

**Issue by sokol2027** [DennoN-RUS/Bird4Static#11]
Добрый. Данный скрипт будет работать на ASUS AX3000v2? Можно адаптировать?

**Comment by DennoN-RUS** [comment]
Установи на роутер entware и попробуй установить. В теории все должно сработать

**Comment by sokol2027** [comment]
При запуске сприата вот так вот.

HomeFolder is /tmp/home/root/Bird4Static
SystemFolder is /tmp/home/root/Bird4Static/opt
./Bird4Static/install.sh: line 221: /tmp/home/root/Bird4Static/opt/bin/opkg: not found
./Bird4Static/install.sh: line 221: /tmp/home/root/Bird4Static/opt/bin/opkg: not found
./Bird4Static/install.sh: line 221: /tmp/home/root/Bird4Static/opt/bin/opkg: not found
