### ISSUE TITLE
Игнорируется user-isp.list

### ISSUE THREAD

**Issue by progist1** [DennoN-RUS/Bird4Static#15]
Здравствуйте!
Потерялся доступ к сайту lknpd.nalog.ru, похоже, прокидывается через VPN, и блокируется хостом.
Добавил в user-isp.list строки:
```
lknpd.nalog.ru
213.24.64.181
213.24.64.0/24
```
пропатчил списки:
```
~/Bird4Static # ./scripts/add-bird4_routes.sh 
patching file /opt/etc/bird4-force-isp.list
Restarting bird
```

tracert:
```
tracert lknpd.nalog.ru

Tracing route to lknpd.gi.nalog.ru [213.24.64.181]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  direct.router.home [10.0.0.1]
  2  10.4.0.74  reports: Destination host unreachable.

Trace complete.
```
Вообще, 10.4.0.74 — IP провайдера.
```
~/Bird4Static # ./uninstall.sh 
Begin uninstall? y/n
y
<...>
```

tracert после удаления B4S:
```
tracert lknpd.nalog.ru

Tracing route to lknpd.gi.nalog.ru [213.24.64.181]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  direct.router.home [10.0.0.1]
  2     3 ms     3 ms     3 ms  ... [...]
  3     7 ms     4 ms     4 ms  ... [...]
  4    12 ms    11 ms    11 ms  46.61....
  5    12 ms    21 ms    12 ms  46.61....
<...>
```
ну, и после удаления, доступ появляется :)

Подскажите, что делаю не так?

**Comment by DennoN-RUS** [comment]
если у тебя после роутера direct.router.home [10.0.0.1]
идет обращение к  10.4.0.74 и это ip провейдера, то траффик как раз идет через провайдера. Но видимо нужно зайти в вики и в Известных проблемах прочитать [пункт 2](https://github.com/DennoN-RUS/Bird4Static/wiki/%D0%94%D0%B8%D0%B0%D0%B3%D0%BD%D0%BE%D1%81%D1%82%D0%B8%D0%BA%D0%B0#%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B)

**Comment by progist1** [comment]
Спасибо, попробую)
