### ISSUE TITLE
Захватывать поддомены

### ISSUE THREAD

**Issue by dartraiden** [DennoN-RUS/Bird4Static#16]
В user-vpn2.list добавляю домены, владельцы которых запрещают доступ из РФ. Сервер VPN2, само собой, расположен за пределами РФ.

Столкнулся с тем, что если добавить домен верхнего уровня, то через VPN проксируется именно он, но не его поддомены.

Например, если добавить `vaio.com`, то невозможно, скачать файл https://csdlcdn.vaio.com/supportfiles/update/SP000623.exe, т.к. трафик не направляется в VPN, ресурс видит, что я захожу через своего провайдера из России, и блокирует доступ. Только если явно добавить `csdlcdn.vaio.com` в user-vpn2.list, файл удаётся скачать.

Есть ли возможность при указании домена автоматически захватывать и все его поддомены?

**Comment by DennoN-RUS** [comment]
К сожаленю нельзя. bird не работает по факту по доменам, он работает по ip адресам этих доменов. При указании в листе домена - домен превращается в ip адрес. И если у vaio.com и csdlcdn.vaio.com разные ip адреса, то bird ничего сделать не сможет. + у csdlcdn.vaio.com вообще cdn, а это значит что 1 раз этот домен может быть на одних ip адресах, а в другом случае на других.
В случае с csdlcdn.vaio.com можно добавить всю AS, а именно - AS8075, но тогда все ip адреса 13.64.0.0-13.107.255.255  пойдут в тунель
https://ipinfo.io/13.107.246.53
