### ISSUE TITLE
Замедление YouTube

### ISSUE THREAD

**Issue by Anonym-tsk** [DennoN-RUS/Bird4Static#17]
Кинетик из коробки умеет для определенных доменов использовать другой DNS. Настраивается где-то в правилах.

Хотелось бы иметь какую-то возможность перенаправить весь трафик *.googlevideo.com в VPN, но там тысячи адресов и вычислить все очень сложно.

Идея состоит в том, чтобы детектить запрос к *.googlevideo.com и заворачивать в ВПН в рантайме. Как - пока непонятно.

Предлагаю подумать и обсудить.

**Comment by DennoN-RUS** [comment]
Это уже не будет решение, основанное, на маршрутах, списках бгп и тд. И реализовываться это будет не через маршруты, а через фаервол. Так что в этом проекте такого точно не будет. Были темы  с ipset списком заполнением его через днс и заворачиванием этого списка в фаерволл. На форуме кинетика было, возможно потерли уже.

**Comment by DennoN-RUS** [comment]
https://pimpmykeenetic.github.io/2022/12/17/adguardhome-and-selective-routing.html
Вот инструкция

**Comment by Anonym-tsk** [comment]
Есть даже решение через ipset-dns, который добавляет маршруты в рантайме. Может как-то объединить в одно решение?

**Comment by butaford** [comment]
Используйте сервис antifilter.network, там есть лист youtube

**Comment by Anonym-tsk** [comment]
> там есть лист youtube

Не вижу такого списка

**Comment by butaford** [comment]
> Не вижу такого списка

![Screenshot_2024-08-05-17-41-47-164_com android chrome](https://github.com/user-attachments/assets/ec77335e-92d7-4a2d-b030-8975fe1f14fa)

**Comment by DennoN-RUS** [comment]
Сделал IPset4Static https://github.com/DennoN-RUS/IPset4Static
И обновил Bird4Static для работы с ним. но можно и отдельно ставить без bird

**Comment by Anonym-tsk** [comment]
Круто, но я пошел другим путём и сделал свое решение https://github.com/Anonym-tsk/tpws-keenetic

**Comment by DennoN-RUS** [comment]
О. Тоже прикольная вещь
