### ISSUE TITLE
Как удалить версию v2 или обновиться на версию 3?

### ISSUE THREAD

**Issue by FlyingHavoc** [DennoN-RUS/Bird4Static#2]
Уже установлен пакет из версии v2.
Как удалить версию v2?

Если уже установлена версия v2, возможен ли прямой апгрейд на версию v3?

**Comment by DennoN-RUS** [comment]
Нужно удалить:
rm /opt/etc/cron.daily/add-bird4_routes.sh
rm /opt/etc/ndm/ifstatechanged.d/010-add_antizapret_route.sh
Желательно удалить (что бы было меньше неиспользуемых файлов):
rm /opt/etc/bird4-routes.list
rm -R /opt/root/Bird4Static - вот тут аккуратно, если есть свои листы перенаправления, то лучше их скопировать в другое место, что бы потом восстановить

ну а дальше установка
git clone https://github.com/DennoN-RUS/Bird4Static.git
chmod +x ./Bird4Static/install.sh
./Bird4Static/install.sh
